services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://archive.org/download/Win8Build8330Debombed/%E6%8B%86%E5%BC%B9%E9%95%9C%E5%83%8FWindows%208%20build%208330%20fbl_grfx_dev1%28x64%29%20debombed.iso"
      RAM_SIZE: "8G"
      CPU_CORES: "2"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
      - ./winc:/data  
    restart: always
    stop_grace_period: 2m
